### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by endcoreCL** [antistatique/pricehubble-php-sdk#10]
Thanks for this repo. 

I can not install the package unfortunately:

[InvalidArgumentException]
Could not find a matching version of package antistatique/pricehubble-php-sdk. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by WengerK** [comment]
Hey @endcoreCL ... sorry for the huge delay ... did not saw the notification.

We will release during this week the project, for now you must add it using the branch ....

```
composer require antistatique/pricehubble-php-sdk:dev-main
```

and add the VCS

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/antistatique/pricehubble-php-sdk"
        }
    ],
```

**Comment by WengerK** [comment]
Here, with the release of today, you can install the project whitout anything else than

```
composer require antistatique/pricehubble-php-sdk
```
